# A Quick Introduction To NumPy
The NumPy library offers efficient numerical procedures that simplify complex calculations. The fundamental object in this library is the NumPy array. Like Pandas, NumPy must be imported before use. Depending on your notebook, you may need to install NumPy before importing it.

The example code cell below uses a <font color='green'>try</font> and <font color='green'>except</font> code block to import NumPy and assigns<br> it the common alias <font color='green'>np</font>.$^{1}$



---
$^{1}$ For a discusion of  <font color='green'>try</font> and <font color='green'>except</font> code blocks see Chapter *Control Statements*.



In [1]:
try:
  import numpy as np
except:
  !pip install numpy
  import numpy as np

## A One Dimensional Array
The <font color='green'>array()</font> method uses iterable data, such as a list, as its argument to generate NumPy arrays. For instance, an array containing the numbers 1, 2, and 3 can be created from a list.$^{2}$

---
$^{2}$ If you need a little help with this concept see Chapter *A First Look At Lists*.

In [2]:
data=[1,2,3]
x=np.array(data)
x

array([1, 2, 3])

Three Important Attributes Of Arrays
The array attribute <font color='green'>ndim</font> is the number of axes or dimensions of an array.  The <font color='green'>shape</font> attribute is the<br> size of an array on each axis.  The type of data is dtype. The array <font color='green'>x</font> has one axis, the size of the axis is<br> three, and <font color='green'>dtype</font>  are 64 byte integers.

In [3]:
print('Number Of Axes',np.array(x).ndim)
print('Size Of Axes',np.array(x).shape)
print('Type Of Data',np.array(x).dtype)

Number Of Axes 1
Size Of Axes (3,)
Type Of Data int64


## Element-By-Element Calculations
Calculations on NumPy arrays are element by element creating a new array of<br> results with size attribute of three.  Here results are demonstrated with two<br> one-dimensional arrays.

In [4]:
y=np.array([4,5,6])    #Create  the NumPy array y from a list with array() method
x_times_y=x*y
print('Multiplication',x_times_y)
log_x=np.log(x)
print('Natural Log Of x',log_x)
euler_to_x=np.exp(x)
print('Raising e To x',euler_to_x)

Multiplication [ 4 10 18]
Natural Log Of x [0.         0.69314718 1.09861229]
Raising e To x [ 2.71828183  7.3890561  20.08553692]


## Multi-Dimensional Arrays
Numpy arrays cam have any number of dimensions.  Our attention is limited to two:


1.   One-dimensional arrays: These are single-row vectors (1 x n).
2.   Two-dimensional arrays: These are matrices with multiple rows (m x n), including m x 1 column vectors.


A Simple Two-Dimensional Array
A column vector represents the simplest multi-dimensional array. An array is generated from a nested list of the integers one, two, and three. This array has two dimensions (<font color='green'>ndim</font>) and its rows and columns (<font color='green'>shape</font>) are three and one, respectively.

In [5]:
z=np.array([[1],[2],[3]])
display(z)
display(z.ndim)
display(z.shape)

array([[1],
       [2],
       [3]])

2

(3, 1)

Transposing Arrays Or Matrices
<font color='green'>array_method</font> with two rows and three columns is transposed and assigned to<br> <font color='green'>transpose_array</font> with three rows and two columns The sole argument of <font color='green'>transpose()</font><br> is the array that is to be transposed.

In [6]:
#create two dimensitional array: array_method
array_method=np.array([[1,2,3],[4,5,6]])

In [7]:
#transpose array_method from (2,3) shape to (3,2) share
transpose_array=np.transpose(array_method)
print('Shape Of array_method',array_method.shape,
      'Shape of transpose_array',transpose_array.shape)
print(array_method)
print(transpose_array)

Shape Of array_method (2, 3) Shape of transpose_array (3, 2)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Multiplying Arrays
The number of columns in the first matrix must equal the number of rows in the second matrix<br> in order to perform matrix multiplication. The resulting matrix has elements that are equal to<br> the sum product of the columns and rows. These elements are indexed by the rows and<br> columns. The NumPy method <font color='green'>matmul()</font> can be used to multiply two conforming matrices.<br> In the example provided, <font color='green'>array_method</font> is the first matrix and <font color='green'>transpose_array</font> is the second<br> matrix. Because <font color='green'>transpose()</font> converts rows to columns, the number of columns of the original matrix will equal number of rows of the transposed matrix. The result is <font color='green'>multiplied_array</font>, a square matrix with two rows and two columns.$^{3}$

---

$^{3}$The volumes use the <font color='green'>matmul()</font> method to multiply matrices; the ampersand symbol (@) can also be used for this purpose,<br> but <font color='green'>matmul()</font> is preferred for clarity.

In [8]:
multiplied_array=np.matmul(array_method,transpose_array)
multiplied_array

array([[14, 32],
       [32, 77]])

Inverting Matrices
The NumPy module <font color='green'>linalg</font> includes the <font color='green'>inv()</font> method that returns the inverse of<br> a square matrix. This is often necessary for numerical and statistical calculations.<br> The inverse of multiplied array is calculated using <font color='green'>np.linalg.inv()</font> and then multiplied into <br> <font color='green'>multiplied_array</font>. This results in the identity matrix, with ones on the main diagonal<br> and zeros everywhere else.

In [9]:
inverse_multiplied_array=np.linalg.inv(multiplied_array)
np.matmul(inverse_multiplied_array,multiplied_array)

array([[1., 0.],
       [0., 1.]])

NumPy Arrays Are Iterable
NumPy arrays can be sliced or iterated through. In the example, the <font color='green'>multiplied_array</font> is<br> first sliced, and then its rows are iterated over.

In [10]:
first_row=multiplied_array[0:1]
second_row=multiplied_array[1:]
print('First & Second Rows',first_row,'&',second_row)
for row_number,array in enumerate(multiplied_array[0:]):
  print('Row Number & Row Array',row_number,' & ',array)

First & Second Rows [[14 32]] & [[32 77]]
Row Number & Row Array 0  &  [14 32]
Row Number & Row Array 1  &  [32 77]


## Vectorize Functions
The NumPy function <font color='green'>vectorize()</font> allows passing NumPy arrays to functions that manipulate scalars or single values.  It's different from the vectorization of calculations achieved by direct NumPy calculations such as multiplying two arrays. In the example, the function does operate on the arrays and benefits from vectorizing the calculations.

In [11]:
def myfunc(a, b):
  "Return a-b if a>b, otherwise return a+b"
  if a > b:
      return a - b
  else:
      return a + b
vfunc = np.vectorize(myfunc)
vfunc(np.array([1, 2, 3, 4]),
      np.array([2, 1, 4, 3]))

array([3, 1, 7, 1])